added simple tests to my makefile for ex04

diff --git a/ex04/Makefile b/ex04/Makefile
--- a/ex04/Makefile
+++ b/ex04/Makefile
@@ -10,6 +10,7 @@ RM          = rm -rf
 GRAY        = \033[38;5;244m
 CURSIVE	   := \033[33;3m
 INDIGO     := \033[38;5;057m
+RED	   := \033[0;31m
 DEF_COLOUR  = \033[0m
 
 all: $(NAME)
@@ -39,7 +40,30 @@ fclean: clean
 	@echo "Removing executable..."
 	@$(RM) $(NAME)
 	@$(RM) tags
+	@$(RM) test*
+	@$(RM) diffs
+
+tests:
+	@make --no-print-directory re
+	@echo "aaaaa" > test1
+	@echo -e "a\n\nb\n\nab\n\ncab\n\n" > test2
+	@printf "" > test3
+	@./$(NAME) test1 a b
+	@./$(NAME) test2 a z
+	@./$(NAME) test3 a b
+	@sed 's/a/b/g' test1 > test1.sed
+	@sed 's/a/z/g' test2 > test2.sed
+	@sed 's/a/b/g' test3 > test3.sed
+	@diff test1.replace test1.sed >> diffs || true
+	@diff test2.replace test2.sed >> diffs || true
+	@diff test3.replace test3.sed >> diffs || true
+	@if [ ! -s diffs ]; then \
+		echo "$(INDIGO)No diffs$(DEF_COLOUR)"; \
+	else \
+		echo "$(RED)ERROR$(DEF_COLOUR)"; \
+	fi
+
 
 re: fclean all
 
-.PHONY: all clean fclean re
+.PHONY: all clean fclean re tests
